### ISSUE TITLE
Is infection.txt intentionally in git?

### ISSUE THREAD

**Issue by TimWolla** [web-auth/cose-lib#5]
### Version(s) affected

Current git master

### Description

Is it intentional that this file exists in git:

https://github.com/web-auth/cose-lib/blob/v4.0/infection.txt?

If it is, then it should be added to `.gitattributes` as `export-ignore`, otherwise consumers will need to download 250kB of useless text.

### How to reproduce

Look at the git repository.

### Possible Solution

Delete the file.

**Comment by TimWolla** [comment]
I see that `.gitattributes` already contains the file because of #4: https://github.com/web-auth/cose-lib/blob/v4.0/.gitattributes. It would be useful if you could release a new version for this, it greatly reduces download sizes which is a good thing for everyone.

**Comment by Spomky** [comment]
Hi @TimWolla,

No this file should not be present at all.
I removed it and it will be ignored.
Tagged `v4.0.5`.

Many thanks for this.

**Comment by TimWolla** [comment]
Thanks, I can confirm it looks good to me now:

```
web-auth/cose-lib:
total 21K
drwxrwx--- 1 *snip* *snip* 4.0K Aug  4 18:48 ./
drwxrwx--- 1 *snip* *snip*    0 Aug  4 18:51 ../
-rwxrwx--- 1 *snip* *snip* 1.9K Aug  4 18:48 composer.json*
-rwxrwx--- 1 *snip* *snip* 1.1K Aug  4 18:48 LICENSE*
-rwxrwx--- 1 *snip* *snip* 1.2K Aug  4 18:48 README.md*
-rwxrwx--- 1 *snip* *snip*  456 Aug  4 18:48 SECURITY.md*
drwxrwx--- 1 *snip* *snip* 4.0K Aug  4 18:48 src/
```
