### ISSUE TITLE
Check of key type and curve assume value is int

### ISSUE THREAD

**Issue by Gashmob** [web-auth/cose-lib#55]
### Version(s) affected

4.2.0

### Description

When you check fields 1 and -1 of an OKP key, you assume the value is an integer, or following rfc9053, it can also be a text string. So if I have a registered key and the cbor map contains tstr as values and not integer, `verify` throw an exception.

Linked to issue 448 of `web-auth/webauthn-framework` (https://github.com/web-auth/webauthn-framework/issues/448)

### How to reproduce

With this binary key:
```
0xA401634F4B50032720674564323535313921582098C91448E657A3366C3C04551DAFD92A8BB2BA35138B4ACB94CA1E79D2627BAE
```
```js
{1: "OKP", 3: -8, -1: "Ed25519", -2: h'98C91448E657A3366C3C04551DAFD92A8BB2BA35138B4ACB94CA1E79D2627BAE'}
```
Currently the lib throw an exception but the key is valid.

**Comment by Spomky** [comment]
Fixed by #56

**Comment by Gashmob** [comment]
Thanks for the pr. But there is also the kty (1) field that can be a string. In class `Key` you have the integers for each key types, but it can also be a string: `'OKP'` for example.

**Comment by Spomky** [comment]
😅

**Comment by Spomky** [comment]
This should be fixed for types as well.
Let me know if there is any issue.

**Comment by Gashmob** [comment]
Sorry but currently not, I've tried from my pending fix on `webauthn-framework`. I've pushed the tests so you can try. If I use the last version of `cose-lib` it throw an exception for unsupported curve from `EdDSA::verify`.
