### ISSUE TITLE
COSE_ALGORITHM_EdDSA contains a lowercase letter

### ISSUE THREAD

**Issue by szepeviktor** [web-auth/cose-lib#8]
### Version(s) affected

4.0.5

### Description

https://github.com/web-auth/cose-lib/search?q=COSE_ALGORITHM_EdDSA 👀 

### How to reproduce

-

### Possible Solution

Change it to `COSE_ALGORITHM_EDDSA`

**Comment by Spomky** [comment]
Indeed. I will fix that in the next release.

**Comment by Spomky** [comment]
Now deprecated.
